apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-nodejs-app.fullname" . }}
type: Opaque
stringData:
  HOST: "{{ .Values.db.host }}"
  PORT: "{{ .Values.db.port }}"
  USERNAME: "{{ .Values.db.username }}"
  PASSWORD: "{{ .Values.db.password }}"
  DATABASE: "{{ .Values.db.database }}"
