apiVersion: v1
kind: Secret
metadata:
  name: { { include "my-nodejs-app.fullname" . } }
type: Opaque
stringData:
  DATABASE_URL: { { .Values.secret.DATABASE_URL | quote } }
  JWT_SECRET: { { .Values.secret.JWT_SECRET | quote } }
