version: "3.9"

services:
  nest-api:
    container_name: nest-api-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nest-api:dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    command: npm run start:dev # Hot reload enabled
    volumes:
      - ../codes:/app # Live auto-reload for developers
      - /app/node_modules # Prevent host override
    user: root # Allow install, debug in dev
    stdin_open: true
    tty: true
